services:
  app:
    image: qingpwq/sai-forum:latest
    container_name: sai-forum
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - SECURITY_SALT=${SECURITY_SALT}
      - GIT_CLIENT_ID=${GIT_CLIENT_ID}
      - GIT_CLIENT_SECRET=${GIT_CLIENT_SECRET}
    volumes:
      - ./sai-forum/images:/tmp/sai-forum/images   # 图床
      - ./logs:/app/logs   # 图床
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: sai-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql   # Mysql数据
      - ./mysql-schema:/docker-entrypoint-initdb.d # 启动脚本
    networks:
      - app-network

  redis:
    image: redis:6.2
    container_name: sai-redis
    volumes:
      - redis-data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sai-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: sai-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: sai-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mysql-data
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  app-network:
    driver: bridge
