server:
  port: 8080
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟
  address: 0.0.0.0

spring:
  application:
    name: sai-forum
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  config:
    import:
      - application-dal.yml
      - application-email.yml
      - application-monitor.yml
      - application-rabbitmq.yml
      - application-image.yml
      - application-ai.yml

database:
  name: sai-forum

jwt:
  key: ${JWT_KEY}

security:
  salt: ${SECURITY_SALT}
  salt-index: ${SECURITY_SALT_INDEX:2}

msg:
  welcome: "欢迎来到SAI学院技术论坛！"

sensitive:
  enable: true

# OAuth2
github:
  client-id: ${GIT_CLIENT_ID}
  client-secret: ${GIT_CLIENT_SECRET}