server:
  port: 8080
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟
  address: 0.0.0.0

spring:
  main:
    allow-circular-references: true
  config:
    import: application-dal.yml, application-image.yml


database:
  name: sai-forum

jwt:
  key: sai-key

security:
  salt: sai-salt
  salt-index: 2

msg:
  welcome: "欢迎来到SAI论坛！"