# 监控系统
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 开启所有的端点
    # 配置暴露 prometheus，并允许将我的列表导入到 Prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS
  prometheus:
    metrics:
      export:
        enabled: true
