langchain4j:
  open-ai:
    chat-model:
      base-url: ${openai.base-url}
      api-key: ${openai.api-key}
      model-name: ${openai.model-name}
      log-requests: true
      log-responses: false

openai:
  api-key:
  model-name:
  base-url: