spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
  dynamic:
    primary: master
    datasource:
      master:
        # 数据库名，从配置 database.name 中获取
        url: jdbc:mysql://mysql:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password:
      slave:
        # 数据库名，从配置 database.name 中获取
        url: jdbc:mysql://mysql:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password:
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl